# Generated by Django 4.2.5 on 2023-10-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Авторизация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='іmage',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/', verbose_name='Картинка'),
        ),
    ]
