# Generated by Django 4.2.5 on 2023-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('try_status', models.CharField(max_length=50, verbose_name='Статус попытки')),
                ('server_answer', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Время начала рассылки')),
                ('time_end', models.DateTimeField(verbose_name='Время окончания рассылки')),
                ('period', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=30, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('create', 'Создана'), ('started', 'Запущена'), ('ended', 'Завершена')], default='create', max_length=30, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
