# Generated by Django 4.2.5 on 2023-10-07 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='last_try_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время последней попытки'),
        ),
    ]
